version: '3.7'
services:
    app:
        build: ./app
        restart: always
        ports:
            - "3000:3000"
        links:
            - db
    db:
        image: mysql:5.7
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=alphaCTF2022
            - MYSQL_DATABASE=sequelae
